module.exports = [
"I feel the love of those who are not physically around me.",
"I take pleasure in my own solitude.",
"I am too big a gift to this world to feel self-pity.",
"I love and approve of myself.",
"I focus on breathing and grounding myself.",
"Following my intuition and my heart keeps me safe and sound.",
"I make the right choices every time.",
"I draw from my inner strength and light.",
"I trust myself.",
"I am a unique child of this world.",
"I have as much brightness to offer the world as the next person.",
"I matter and what I have to offer this world also matters.",
"I may be one in 7 billion but I am also one in 7 billion.",
"I trust my inner wisdom and intuition.",
"I breathe in calmness and breathe out nervousness.",
"This situation works out for my highest good.",
"Wonderful things unfold before me.",
"I forgive myself for all the mistakes I have made.",
"I let go of my anger so I can see clearly.",
"I accept responsibility if my anger has hurt anyone.",
"I replace my anger with understanding and compassion.",
"I offer an apology to those affected by my anger.",
"I may not understand the good in this situation but it is there.",
"I muster up more hope and courage from deep inside me.",
"I choose to find hopeful and optimistic ways to look at this.",
"I kindly ask for help and guidance if I cannot see a better way.",
"I refuse to give up because I haven’t tried all possible ways.",
"I know my wisdom guides me to the right decision.",
"I trust myself to make the best decision for me.",
"I receive all feedback with kindness but make the final call myself.",
"I listen lovingly to this inner conflict and reflect on it until I get to peace around it.",
"I love my family even if they do not understand me completely.",
"I show my family how much I love them in all the verbal and non-verbal ways I can.",
"There is a good reason I was paired with this perfect family.",
"I choose to see my family as a gift.",
"I am a better person from the hardship that I’ve gone through with my family.",
"I choose friends who approve of me and love me.",
"I surround myself with people who treat me well.",
"I take the time to show my friends that I care about them.",
"My friends do not judge me, nor do they influence what I do with my life.",
"I take great pleasure in my friends, even if we disagree or live different lives.",
"I am beautiful and smart and that’s how everyone sees me.",
"I take comfort in the fact that I can always leave this situation.",
"I never know what amazing incredible person I will meet next.",
"The company of strangers teaches me more about my own likes and dislikes.",
"I am doing work that I enjoy and find fulfilling.",
"I play a big role in my own career success.",
"I ask for and do meaningful, wonderful and rewarding work.",
"I engage in work that impacts this world positively.",
"I believe in my ability to change the world with the work that I do.",
"Peaceful sleep awaits me in dreamland.",
"I let go of all the false stories I make up in my head.",
"I release my mind of thought until the morning.",
"I embrace the peace and quiet of the night.",
"I sleep soundly and deeply and beautifully into this night.",
"This day brings me nothing but joy.",
"Today will be a gorgeous day to remember.",
"My thoughts are my reality so I think up a bright new day.",
"I fill my day with hope and face it with joy.",
"I choose to fully participate in my day.",
"I let go of worries that drain my energy.",
"I make smart, calculated plans for my future.",
"I am a money magnet and attract wealth and abundance.",
"I am in complete charge of planning for my future.",
"I trust in my own ability to provide well for my family.",
"I follow my dreams no matter what.",
"I show compassion in helping my loved ones understand my dreams.",
"I ask my loved ones to support my dreams.",
"I answer questions about my dreams without getting defensive.",
"My loved ones love me even without fully grappling with my dreams.",
"I accept everyone as they are and continue on with pursuing my dream.",
"I am safe and sound. All is well.",
"Everything works out for my highest good.",
"There is a great reason this is unfolding before me now.",
"I have the smarts and the ability to get through this.",
"All my problems have a solution.",
"I attempt all – not some – possible ways to get unstuck.",
"I seek a new way of thinking about this situation.",
"The answer is right before me, even if I am not seeing it yet.",
"I believe in my ability to unlock the way and set myself free.",
"I have no right to compare myself to anyone for I do not know their whole story.",
"I compare myself only to my highest self.",
"I choose to see the light that I am to this world.",
"I am happy in my own skin and in my own circumstances.",
"I see myself as a gift to my people and community and nation.",
"I am more than good enough and I get better every day.",
"I give up the habit to criticize myself.",
"I adopt the mindset to praise myself.",
"I see the perfection in all my flaws and all my genius.",
"I fully approve of who I am, even as I get better.",
"I am a good person at all times of day and night.",
"I cannot give up until I have tried every conceivable way.",
"Giving up is easy and always an option so let’s delay it for another day.",
"I press on because I believe in my path.",
"It is always too early to give up on my goals.",
"I must know what awaits me at the end of this rope so I do not give up.",
"The past has no power over me anymore",
"I embrace the rhythm and the flowing of my own heart.",
"All that I need comes to me at the right time and place in this life.",
"I am deeply fulfilled with who I am."
]