module.exports = [
"I feel the love of those who are not physically around me.",
"I take pleasure in my own solitude.",
"I am too big a gift to this world to feel self-pity.",
"I love and approve of myself.",
"I focus on breathing and grounding myself.",
"Following my intuition and my heart keeps me safe and sound.",
"I make the right choices every time.",
"I draw from my inner strength and light.",
"I trust myself.",
"I am a unique child of this world.",
"I have as much brightness to offer the world as the next person.",
"I matter and what I have to offer this world also matters.",
"I may be one in 7 billion but I am also one in 7 billion.",
"I trust my inner wisdom and intuition.",
"I breathe in calmness and breathe out nervousness.",
"This situation works out for my highest good.",
"Wonderful things unfold before me.",
"I forgive myself for all the mistakes I have made.",
"I let go of my anger so I can see clearly.",
"I accept responsibility if my anger has hurt anyone.",
"I replace my anger with understanding and compassion.",
"I offer an apology to those affected by my anger.",
"I may not understand the good in this situation but it is there.",
"I muster up more hope and courage from deep inside me.",
"I choose to find hopeful and optimistic ways to look at this.",
"I kindly ask for help and guidance if I cannot see a better way.",
"I refuse to give up because I haven’t tried all possible ways.",
"I know my wisdom guides me to the right decision.",
"I trust myself to make the best decision for me.",
"I receive all feedback with kindness but make the final call myself.",
"I listen lovingly to this inner conflict and reflect on it until I get to peace around it.",
"I love my family even if they do not understand me completely.",
"I show my family how much I love them in all the verbal and non-verbal ways I can.",
"There is a good reason I was paired with this perfect family.",
"I choose to see my family as a gift.",
"I am a better person from the hardship that I’ve gone through with my family.",
"I choose friends who approve of me and love me.",
"I surround myself with people who treat me well.",
"I take the time to show my friends that I care about them.",
"My friends do not judge me, nor do they influence what I do with my life.",
"I take great pleasure in my friends, even if we disagree or live different lives.",
"I am beautiful and smart and that’s how everyone sees me.",
"I take comfort in the fact that I can always leave this situation.",
"I never know what amazing incredible person I will meet next.",
"The company of strangers teaches me more about my own likes and dislikes.",
"I am doing work that I enjoy and find fulfilling.",
"I play a big role in my own career success.",
"I ask for and do meaningful, wonderful and rewarding work.",
"I engage in work that impacts this world positively.",
"I believe in my ability to change the world with the work that I do.",
"Peaceful sleep awaits me in dreamland.",
"I let go of all the false stories I make up in my head.",
"I release my mind of thought until the morning.",
"I embrace the peace and quiet of the night.",
"I sleep soundly and deeply and beautifully into this night.",
"This day brings me nothing but joy.",
"Today will be a gorgeous day to remember.",
"My thoughts are my reality so I think up a bright new day.",
"I fill my day with hope and face it with joy.",
"I choose to fully participate in my day.",
"I let go of worries that drain my energy.",
"I make smart, calculated plans for my future.",
"I am a money magnet and attract wealth and abundance.",
"I am in complete charge of planning for my future.",
"I trust in my own ability to provide well for my family.",
"I follow my dreams no matter what.",
"I show compassion in helping my loved ones understand my dreams.",
"I ask my loved ones to support my dreams.",
"I answer questions about my dreams without getting defensive.",
"My loved ones love me even without fully grappling with my dreams.",
"I accept everyone as they are and continue on with pursuing my dream.",
"I am safe and sound. All is well.",
"Everything works out for my highest good.",
        "A friend's frown is better than a fool's smile.",
        "A friend in need is a friend indeed.",
        "A friend is easier lost than found.",
        "A friend to everybody is a friend to nobody.",
        "A problem shared is a problem halved.",
        "A true friend is someone who reaches for your hand, but touches your heart.",
        "False friends are worse than open enemies.",
        "Flattery is all right so long as you don't inhale.",
        "Give credit where credit is due.",
        "Grief divided is made lighter.",
        "Memory is the treasure of the mind.",
        "Nothing dries sooner than a tear.",
        "Old friends and old wine are best.",
        "The best of friends must part.",
        "The best things are not bought and sold.",
        "There is no better looking-glass than an old friend.",
        "To err is human (To forgive divine).",
        "Two cannot fall out if one does not choose.",
          "A bully is always a coward.",
        "A handsome shoe often pinches the foot.",
        "A good thing is all the sweeter when won with pain.",
        "A person too careful of danger lives in continual torment.",
        "A miss is as good as a mile.",
        "Adversity flatters no person.",
        "Adversity and loss make a person wise.",
        "All promises are either broken or kept.",
        "All things come to those that wait.",
        "An eye for an eye and a tooth for a tooth.",
        "An open door may tempt a saint.",
        "As one door closes, another always opens.",
        "As you go through life, make this your goal, watch the doughnut and not the hole.",
        "Brevity is the soul of wit.",
        "Cut your coat according to the cloth.",
        "Discretion is the better part of valour.",
        "Do right and fear no person.",
        "Easy come, easy go.",
        "Experience is the hardest teacher. They gives the test first and the lesson afterwards.",
        "Familiarity breeds contempt.",
        "Fortune favours the brave.",
        "They who laughs last, laughs longest.",
        "Home is where the heart is.",
        "Hope for the best and prepare for the worst.",
        "If wishes were horses, beggars would ride.",
        "In the country of the blind, the one-eyed person is king.",
        "It never rains but it pours.",
        "Leave tomorrow till tomorrow.",
        "Life begins at forty.",
        "Lifes trials may be hard to bear, but patience can outlive them.",
        "Live and learn.",
        "Manners maketh the person.",
        "No person is worse for knowing the worst of himself.",
        "Only the good die young.",
        "Procrastination is the thief of time.",
        "The best things in life are free.",
        "The family that prays together, stays together.",
        "The longer you live the more you see.",
        "The meek shall inherit the earth.",
        "The receiver is as bad as the thief.",
           "After dinner rest a while, after supper walk a mile.",
        "An apple a day keeps the doctor away.",
        "A drowning person will clutch at a straw.",
        "An onion a day keeps everyone away.",
        "Another pot ! Try the teapot.",
        "As fit as a fiddle.",
        "As hard as nails.",
        "As sick as a dog.",
        "As you go through life, make this your goal, watch the doughnut and not the hole.",
        "Be not a baker if your head is made of butter.",
        "Beauty is but skin deep.",
        "Better late thrive than never do well.",
        "Better to be poor and healthy rather than rich and sick.",
        "Better to wear out than rust out.",
        "Bread never falls but on its buttered side.",
        "Cleanliness is next to Godliness.",
        "Content is health to the sick and riches to the poor.",
        "Don't bite the hand that feeds you.",
        "Drink like a fish, water only.",
        "Early to bed, early to rise, makes you healthy, wealthy & wise.",
        "Fair words butter no cabbage.",
        "Good wine ruins the purse, and bad wine ruins the stomach.",
        "Greediness burst the bag.",
        "Grumbling makes the loaf no larger.",
        "Half a loaf is better than none.",
        "They who drinks a little too much drinks much too much.",
        "They who rises late must trot all day.",
        "their eyes are bigger than their belly.",
        "Hunger is the best sauce.",
        "It is no use crying over spilt milk.",
        "Old friends and old wine are best.",
        "One person's meat is another person's poison.",
        "Ready money is ready medicine.",
        "Sound as a bell.",
        "The nearer the bone the sweeter the meat.",
        "The proof of the pudding is in the eating.",
        "There's many a slip, twixt cup and the lip.",
        "To add insult to injury.",
        "To look as if butter will not melt in their mouth.",
        "Too many cooks spoil the broth.",
        "What can't be cured must be endured.",
        "What you eat today walks and talks tomorrow.",
        "You are what you eat.",
        "You can't have your cake and eat it too.",
        "You can eat an elephant if you do it one mouthful at a time.",
        "You can't unscramble a scrambled egg.",
        "Wondrous is the strength of cheerfulness.",
        "To wait and be patient soothes many a pang.",
        "Up and down like a fiddler's elbow.",
        "Useless as a screen door on a submarine.",
        "We cannot erase the sad records from our past.",
        "What the eye doesn't see, the heart doesn't grieve over.",
        "While there's life there's hope.",
"There is a great reason this is unfolding before me now.",
"I have the smarts and the ability to get through this.",
"All my problems have a solution.",
"I attempt all – not some – possible ways to get unstuck.",
"I seek a new way of thinking about this situation.",
"The answer is right before me, even if I am not seeing it yet.",
"I believe in my ability to unlock the way and set myself free.",
"I have no right to compare myself to anyone for I do not know their whole story.",
"I compare myself only to my highest self.",
"I choose to see the light that I am to this world.",
"I am happy in my own skin and in my own circumstances.",
"I see myself as a gift to my people and community and nation.",
"I am more than good enough and I get better every day.",
"I give up the habit to criticize myself.",
"I adopt the mindset to praise myself.",
"I see the perfection in all my flaws and all my genius.",
"I fully approve of who I am, even as I get better.",
"I am a good person at all times of day and night.",
"I cannot give up until I have tried every conceivable way.",
"Giving up is easy and always an option so let’s delay it for another day.",
"I press on because I believe in my path.",
"It is always too early to give up on my goals.",
"I must know what awaits me at the end of this rope so I do not give up.",
"The past has no power over me anymore",
"I embrace the rhythm and the flowing of my own heart.",
"All that I need comes to me at the right time and place in this life.",
"I am deeply fulfilled with who I am."
]